debug_mode: 1
server:
  num_processes: 0
  port: 5003
  ssl_key:
  ssl_cert:
pycket:
  redis_host: 127.0.0.1
  redis_port: 6379
  redis_sessions: 14
  redis_notifications: 15
  expires_days: 1
  max_age: 30
storage:
  user_dir: data
ocr:
  work_dir: /home/ray/Workspace/project/ocr/github/gso_server
  lang: ch
mq_name: ocr_queue